### ISSUE TITLE
After running script - all the local /proc /dev/ /sys /run filesystems remain mounted

### ISSUE THREAD

**Issue by julian1** [alpinelinux/alpine-chroot-install#7]
shouldn't the cgroup mounts be unmounted on exit?

**Comment by jirutka** [comment]
The `enter-chroot` script currently doesn’t unmount anything, i.e. it’s not a bug, but missing feature. I’ll add it.

**Comment by hoshsadiq** [comment]
@jirutka I see that you have done the work in the dev branch, could I ask if there's a reason it's not in the master branch?

**Comment by anjandev** [comment]
It might be worthwhile to put warning about this in the readme on how you have to manually umount everything. I ran this script today on my machine and it worked fine. However, after I was done, I wanted to remove `/alpine`. Since I didnt know you had to umount, I ended up nuking my system by running `sudo rm -rf /alpine`....

This is mostly my incompetence but a warning would be good to put in the readme.

**Comment by hoshsadiq** [comment]
@anjandev I've raised an PR to add a destroy script that can automatically delete the chroot as well.

**Comment by anjandev** [comment]
@hoshsadiq thank you. I think it might be worthwhile to document deleting using the destroy script you made rather than merely `rm -rf /alpine`.

**Comment by hoshsadiq** [comment]
It's already mentioned at the end when the script is finished, same way the `enter-chroot` script is mentioned.

**Comment by anjandev** [comment]
@hoshsadiq okay. Thanks!
